apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 1337
      targetPort: 1337
      protocol: TCP
  selector:
    app: spire-server
